#!/usr/bin/env python3
"""Regenerate k8s/platform/analysis-loki.yaml from a readable LogQL query.

Argo's `web` provider puts the query in a URL and does not encode it, so the
query is URL-encoded here once; only {{args.*}} tokens stay raw so Argo can
substitute them (they only ever hold plain names and a hash).

    python3 scripts/gen-loki-analysis.py > k8s/platform/analysis-loki.yaml
"""
import urllib.parse

ARGS = {"ARG_NS": "namespace", "ARG_APP": "app", "ARG_HASH": "canary-hash"}
SELECTOR = '{namespace="ARG_NS", app="ARG_APP", rollouts_pod_template_hash="ARG_HASH"} | json | msg="request"'
QUERY = (
    f"(sum(count_over_time({SELECTOR} | code >= 500 [1m])) or vector(0))"
    f" / sum(count_over_time({SELECTOR} [1m]))"
)

encoded = urllib.parse.quote(QUERY, safe="")
readable = QUERY
for placeholder, arg in ARGS.items():
    encoded = encoded.replace(placeholder, "{{args.%s}}" % arg)
    readable = readable.replace(placeholder, "<%s>" % arg)

print(f'''# GENERATED by scripts/gen-loki-analysis.py; edit the query there, not here.
#
# Shared definition of "the canary is healthy", owned by the platform and used by
# any Rollout in any namespace (ClusterAnalysisTemplate). Rollouts only pass
# parameters; the LogQL query lives here, written once.
#
# Argo Rollouts has no Loki provider, so it asks Loki directly through the
# generic `web` provider: Loki evaluates LogQL over the app's JSON request logs
# (12-factor XI) and returns a number. No Prometheus, no recording rules.
#
# LogQL (args shown as <...>):
#   {readable}
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: loki-error-rate
spec:
  args:
    - name: namespace
    - name: app
    - name: canary-hash
  metrics:
    - name: error-rate
      initialDelay: 20s          # let Alloy ship the first canary request logs
      interval: 15s
      count: 4                   # 4 measurements: the step finishes in ~1 minute
      failureLimit: 1            # one bad sample is tolerated, the second aborts
      consecutiveErrorLimit: 2   # Loki unreachable or no canary logs: fail closed
      successCondition: asFloat(result) <= 0.02
      provider:
        web:
          url: "http://loki.logging.svc:3100/loki/api/v1/query?query={encoded}"
          jsonPath: "{{$.data.result[0].value[1]}}"''')
